{{- if .Values.quickstart.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bctlquickstartchart.quickstartRoleBindingName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
subjects:
    - kind: ServiceAccount
      namespace: {{ .Release.Namespace }}
      name: {{ include "bctlquickstartchart.quickstartServiceAccountName" . }}
roleRef:
    kind: Role
    name: {{ include "bctlquickstartchart.quickstartRoleName" . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}