{{- if .Values.quickstart.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bctlquickstartchart.quickstartJobName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
  namespace: {{ include "bctlquickstartchart.namespace" . }}
spec:
    backoffLimit: 0
    template:
        spec:
            serviceAccountName: {{ include "bctlquickstartchart.quickstartServiceAccountName" . }}
            restartPolicy: Never
            containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              resources:
                {{- toYaml .Values.quickstartResources | nindent 16 }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
              - name: API_KEY
                value: "{{ required "A valid .Values.apiKey entry required!" .Values.apiKey }}"
              - name: CLUSTER_NAME
                value: "{{ required "A valid .Values.clusterName entry required!" .Values.clusterName }}"
              - name: DEPLOYMENT_NAME
                value: "{{ include "bctlquickstartchart.agentDeploymentName" . }}"
              - name: NAMESPACE
                value: "{{ include "bctlquickstartchart.namespace" . }}"
              - name: QUICKSTART_JOB_NAME
                value: "{{ include "bctlquickstartchart.quickstartJobName" . }}"
              - name: SERVICE_URL
                value: "{{ required "A valid .Values.serviceUrl entry required!" .Values.serviceUrl }}"
              command: 
              - bctl-quickstart
              args:
              {{- if .Values.users }}
              {{- range $user := .Values.users }}
              - "-users"
              - "{{ $user }}"
              {{- end }}
              {{- end }}
              {{- if .Values.targetUsers }}
              {{- range $targetUser := .Values.targetUsers }}
              - "-targetUsers"
              - "{{ $targetUser }}"
              {{- end }}
              {{- end }}
              {{- if .Values.targetGroups }}
              {{- range $targetGroup := .Values.targetGroups }}
              - "-targetGroups"
              - "{{ $targetGroup }}"
              {{- end }}
              {{- end }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
              {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
              {{- toYaml . | nindent 8 }}
            {{- end }}
{{- end }}