{{- if .Values.quickstart.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bctlquickstartchart.quickstartRoleName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["watch"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "patch", "list"]
    - apiGroups: ["batch"]
      resources: ["jobs"]
      verbs: ["delete"]
{{- end }}