kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bctlquickstartchart.agentRoleName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "update", "create"]