apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bctlquickstartchart.agentDeploymentName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ include "bctlquickstartchart.agentDeploymentName" . }}
    template:
        metadata:
            labels:
                app: {{ include "bctlquickstartchart.agentDeploymentName" . }}
        spec:
            serviceAccountName: {{ include "bctlquickstartchart.agentServiceAccountName" . }}
            containers:
            - name: bctl-agent
              image: "bastionzero/bctl-agent:{{ required "A valid .Values.image.agentTag entry required!" .Values.image.agentTag }}"
              resources:
                {{- toYaml .Values.agentResources | nindent 16 }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              ports:
              - containerPort: 6001
                name: bctl-port
              env:
              - name: DEV
                value: "true"
              - name: SERVICE_URL
                value: ""
              - name: ACTIVATION_TOKEN
                value: ""
              - name: TARGET_NAME
                value: "{{ required "A valid .Values.clusterName entry required!" .Values.clusterName }}"
              - name: TARGET_ID
                value: ""
              - name: ORG_ID
                value: ""
              - name: IDP_ORG_ID
                value: ""
              - name: IDP_PROVIDER
                value: ""
              - name: IDP_CUSTOM_ISSUER
                value: ""
              - name: ENVIRONMENT
                value: ""
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
                {{- toYaml . | nindent 8 }}
            {{- end }}