apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bctlquickstartchart.agentServiceAccountName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "bctlquickstartchart.namespace" . }}