apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bctlquickstartchart.agentSecretName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "bctlquickstartchart.namespace" . }}
data:
  secret: Y29vbGJlYW5z