apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bctlquickstartchart.cleanupServiceAccountName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: cleanup
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}