kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bctlquickstartchart.cleanupRoleName" . }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: cleanup
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete"]
    resourceNames: [{{ include "bctlquickstartchart.agentSecretName" . }}]
