apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bctlquickstartchart.cleanupJobName" . }}
  annotations:
    "helm.sh/hook": pre-delete # run before delete (we still need the RBAC)
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bctlquickstartchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: cleanup
spec:
  ttlSecondsAfterFinished: 300 # Leave job for 5 minutes if failed/success
  template:
    spec:
      serviceAccountName: {{ include "bctlquickstartchart.cleanupServiceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: cleanup
        image: "curlimages/curl:latest" # alpine + curl
        env:
          - name: BCTL_SECRET_NAME
            value: {{ include "bctlquickstartchart.agentSecretName" . }}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command: 
          - "/bin/sh"
          - "-ec"
          - |
            curl -s -X DELETE -k https://kubernetes.default.svc/api/v1/namespaces/${NAMESPACE}/secrets/${BCTL_SECRET_NAME} \
              -H "Authorization: Bearer $( cat /var/run/secrets/kubernetes.io/serviceaccount/token )" \
              -H "Content-Type: application/json" \
              -H "Accept: application/json" > /dev/null 