replicaCount: 2

clusterName: bz-multi-replica-example
apiKey: <registration-api-key-goes-here>

agent:
  deploymentName: bz-agent
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: bz-agent
